[[redirects]]
  from = "/tickets"
  to = "https://tiqs.com/alfred/events/shop/759"
  status = 302
  force = true # COMMENT: ensure that we always redirect
[[redirects]]
  from = "/vrijwilliger"
  to = "https://forms.gle/XaV3jFVxNhTwtikc7"
  status = 302
  force = true # COMMENT: ensure that we always redirect
